//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpDmTerminal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BpDmTerminal.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If it so, press &quot;Yes&quot;, else press &quot;No&quot;.
        /// </summary>
        public static string ConfirmIfCorrect {
            get {
                return ResourceManager.GetString("ConfirmIfCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOUSE OF MINISTRIES.
        /// </summary>
        public static string DM {
            get {
                return ResourceManager.GetString("DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter IIN or passport number.
        /// </summary>
        public static string EnterIinOrDocnumber {
            get {
                return ResourceManager.GetString("EnterIinOrDocnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System error.
        /// </summary>
        public static string ErrorInfo {
            get {
                return ResourceManager.GetString("ErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIN.
        /// </summary>
        public static string IIN {
            get {
                return ResourceManager.GetString("IIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invited by.
        /// </summary>
        public static string InvitedBy {
            get {
                return ResourceManager.GetString("InvitedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I hereby give my consent for the safety of a one-time pass, as well as its return to the card collector installed at the exit..
        /// </summary>
        public static string Part1 {
            get {
                return ResourceManager.GetString("Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case of loss or damage to the pass, I undertake to restore (provide an pass of the same type and quality)..
        /// </summary>
        public static string Part2 {
            get {
                return ResourceManager.GetString("Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to According to the Art. 917 of the Civil Code of the Republic of Kazakhstan, the injury (property and (or) non-property damage), caused by illegal actions (inaction) to the property or non-property benefits and rights of citizens and legal entities shall be subject to full redress by the person who inflicted the injury. According to the Art. 934 of the Civil Code of the Republic of Kazakhstan, the person responsible for the infliction of injury to compensate for the losses incurred in full or redress injury i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Part3 {
            get {
                return ResourceManager.GetString("Part3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case of loss of the pass, you must contact by phone 4-50-00..
        /// </summary>
        public static string Part4 {
            get {
                return ResourceManager.GetString("Part4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put vour ID document on alass in coresponding frame and press &quot;START&quot;.
        /// </summary>
        public static string Part5 {
            get {
                return ResourceManager.GetString("Part5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass data confirmation.
        /// </summary>
        public static string PassCardInfoConfirmation {
            get {
                return ResourceManager.GetString("PassCardInfoConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that pas data is correct.
        /// </summary>
        public static string PassCardInfoConfirmationCheck {
            get {
                return ResourceManager.GetString("PassCardInfoConfirmationCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass card not found.
        /// </summary>
        public static string PassCardNotFound {
            get {
                return ResourceManager.GetString("PassCardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASS ISSUING TERMINAL.
        /// </summary>
        public static string Terminal {
            get {
                return ResourceManager.GetString("Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
