//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpDmTerminal.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TerminalEntities : DbContext
    {
        public TerminalEntities()
            : base("name=TerminalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PassCardVisitorInfoLog> PassCardVisitorInfoLog { get; set; }
        public virtual DbSet<SearchRequestInfo> SearchRequestInfo { get; set; }
        public virtual DbSet<TerminalInfo> TerminalInfo { get; set; }
    }
}
