//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpDmTerminal.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassCardVisitorInfoLog
    {
        public long Id { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string PassCardVisitorId { get; set; }
        public string RfidNumber { get; set; }
        public string Notice { get; set; }
    }
}
