//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpDmTerminal.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchRequestInfo
    {
        public long Id { get; set; }
        public string IpAddress { get; set; }
        public string SearchValue { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    }
}
